"""many to many project:subject

Revision ID: 1138321ac3f8
Revises: e3b37d231249
Create Date: 2021-06-09 13:31:17.303477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1138321ac3f8'
down_revision = 'e3b37d231249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_subject_association',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'subject_id')
    )
    op.drop_constraint('subject_project_id_fkey', 'subject', type_='foreignkey')
    op.drop_column('subject', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subject_project_id_fkey', 'subject', 'project', ['project_id'], ['id'])
    op.drop_table('project_subject_association')
    # ### end Alembic commands ###
