"""create first migration

Revision ID: 1a8c65bea378
Revises: 
Create Date: 2021-05-29 20:46:15.078717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8c65bea378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=True)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    op.create_table('study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_uid', sa.String(length=100), nullable=True),
    sa.Column('access_number', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.String(length=40), nullable=False),
    sa.Column('patient_name', sa.String(length=40), nullable=False),
    sa.Column('study_date', sa.String(length=15), nullable=True),
    sa.Column('study_description', sa.String(length=50), nullable=True),
    sa.Column('modalities', sa.String(length=20), nullable=True),
    sa.Column('project_title', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_title'], ['project.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_id'), 'study', ['id'], unique=False)
    op.create_index(op.f('ix_study_instance_uid'), 'study', ['instance_uid'], unique=True)
    op.create_table('subject_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['subject_name'], ['subject.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_images_id'), 'subject_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_images_id'), table_name='subject_images')
    op.drop_table('subject_images')
    op.drop_index(op.f('ix_study_instance_uid'), table_name='study')
    op.drop_index(op.f('ix_study_id'), table_name='study')
    op.drop_table('study')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
