"""third migration

Revision ID: c21faa87cc43
Revises: 1138321ac3f8
Create Date: 2021-06-09 13:48:59.706945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21faa87cc43'
down_revision = '1138321ac3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_subject_association_subject_id_fkey', 'project_subject_association', type_='foreignkey')
    op.create_foreign_key(None, 'project_subject_association', 'subject', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_subject_association', type_='foreignkey')
    op.create_foreign_key('project_subject_association_subject_id_fkey', 'project_subject_association', 'project', ['subject_id'], ['id'])
    # ### end Alembic commands ###
