"""fourth migration

Revision ID: d4058e05badb
Revises: c21faa87cc43
Create Date: 2021-06-09 13:58:11.072341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4058e05badb'
down_revision = 'c21faa87cc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
