"""second migration

Revision ID: d4c0685c2654
Revises: b4537c01ead1
Create Date: 2021-05-29 15:51:36.741409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c0685c2654'
down_revision = 'b4537c01ead1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_id', table_name='study')
    op.drop_index('ix_study_instance_uid', table_name='study')
    op.drop_table('study')
    op.drop_index('ix_project_id', table_name='project')
    op.drop_index('ix_project_title', table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_project_title', 'project', ['title'], unique=False)
    op.create_index('ix_project_id', 'project', ['id'], unique=False)
    op.create_table('study',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('instance_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('access_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('study_date', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('study_description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modalities', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('project_title', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_title'], ['project.title'], name='study_project_title_fkey'),
    sa.PrimaryKeyConstraint('id', name='study_pkey')
    )
    op.create_index('ix_study_instance_uid', 'study', ['instance_uid'], unique=False)
    op.create_index('ix_study_id', 'study', ['id'], unique=False)
    # ### end Alembic commands ###
